### ISSUE TITLE
Fluent Builder API for Rules

### ISSUE THREAD

**Issue by phkiener** [DigitecGalaxus/ProjectsRuler#10]
While it's perfectly fine to create rules using only the constructor, it might be beneficial to allow a more fluent style for creating rules. Something like

    Rule.CreateRule("This is a description")
        .For("Package.A")
        .Referencing("Package.A.Contracts")
        .Kind(RuleKind.Forbidden)

Obviously, the names are up to debate. I myself prefer a sentence-like style, e.g. "Check that package X does not reference package Y" translated as 

    Check("Description")
        .That("Package.A")
        .DoesNotReference("Package.B")

but that is just personal preference.

**Comment by boskicthebrain** [comment]
If you find this more readable, just do it! I personally prefer having a list of rules, that I can scan quickly - but then again, that is a personal preference.
